### ISSUE TITLE
Rule ID 0 Unusable

### ISSUE THREAD

**Issue by Iceman248** [luckman212/pf_fwrule_toggle#1]
Get the message below.

`specify rule id, or -l to list rules`

**Comment by luckman212** [comment]
Thanks @Iceman248 

I just pushed an updated version, please re-download and test again.

**Comment by Iceman248** [comment]
Thanks, works fine.

**Comment by Iceman248** [comment]
This is actually back to not working, not n0, but 0 rule ID specifically throws error.

**Comment by luckman212** [comment]
Please try the version I just pushed. I fixed a bug related to `empty()`

**Comment by Iceman248** [comment]
Fixed, thanks.
