### ISSUE TITLE
Possible to add NAT rule toggle?

### ISSUE THREAD

**Issue by Iceman248** [luckman212/pf_fwrule_toggle#2]
I discovered an issue that despite toggling a firewall rule that was created by NAT rule that one overrode the other and I still had to disable it at the NAT level to fix the issue I had, so I was hoping to figure out a way to disable it at the NAT level to get it to work? Thanks.

**Comment by luckman212** [comment]
I added this functionality. The script now lists and operates on both `nat` and `filter` (standard) rule types.

`-l` will now list both types, and prefixing the ruleID with `n` e.g. `pf_fwrule_toggle n3` will toggle NAT rule #3.

Hope this is helpful.

**Comment by Iceman248** [comment]
Awesome! Thanks, again.
