### ISSUE TITLE
Errors when using on new versions of OPNsense

### ISSUE THREAD

**Issue by Iceman248** [luckman212/pf_fwrule_toggle#4]
Getting below errors after one of newer versions of OPNsense. Just updated to 23.1.11, still an issue, not sure when it began, don't have to have this run often.

`[01-Jul-2023 19:57:16 America/Detroit] PHP Fatal error:  Uncaught Error: Call to undefined function shell_safe() in /usr/local/etc/inc/config.inc:260
Stack trace:
#0 /usr/local/etc/inc/config.inc(204): make_config_revision_entry('ruleset updated...')
#1 /path/to/scripts/fwrule_toggle.php(174): write_config('ruleset updated...')
#2 {main}
  thrown in /usr/local/etc/inc/config.inc on line 260
[01-Jul-2023 19:57:25 America/Detroit] PHP Fatal error:  Uncaught Error: Call to undefined function log_error() in /path/to/scripts/fwrule_toggle.php:179
Stack trace:
#0 {main}
  thrown in /path/to/scripts/fwrule_toggle.php on line 179`

**Comment by luckman212** [comment]
Where does it say this runs on OPNsense? If it used to, that was an unexpected bonus. 

Looking at the error you pasted above, seems like they renamed the `log_error()` function, or moved it out of the `config.inc` include somewhere else.

Unfortunately, I don't have any OPNsense installs to test with and don't have time to debug that. If you figure it out, please submit a PR and I will see if I can make the script work on both platforms.

**Comment by Iceman248** [comment]
Except at first, been running it on OPNsense the whole time.

Thanks, will let you know if I figure it out.
